### ISSUE TITLE
Cypress tests fail

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/activity#995]
Check photos for how @skjnldsv fixed it

**Comment by skjnldsv** [comment]
Photos? Or Viewer you mean?

**Comment by nickvergessen** [comment]
Only know this excerpt:
```js
cy.request('/csrftoken').then(({ body }) => {
	const requesttoken = body.token
	cy.request({
		method: 'POST',
		url: '/login',
		body: { user, password, requesttoken },
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
		},
		followRedirect: false,
	})
	cy.request('/apps/files').its('status').should('eq', 200)
})
```


But also maybe instead of copying, the library should be utilized:
https://github.com/nextcloud/nextcloud-cypress

**Comment by skjnldsv** [comment]
The lib is still being built yes

**Comment by nickvergessen** [comment]
Currently the cypress test times out after 6h. So i renamed the workflow so it does jot run anymore

**Comment by joshtrichards** [comment]
Fixed in #1178

**Comment by nickvergessen** [comment]
Still failing on master? https://github.com/nextcloud/activity/actions/runs/10336583800/job/28613195305?pr=1743
